### PR TITLE
Use CTest instad of Google test

### PR DESCRIPTION
**Pull request by tim-gromeyer**
Requires #20 and #21 (or close the other ones and merge this instead)
gtest didn't compile for whatever reason so implemented 3 tests (unzip, zip file, zip folder) using CTest.
To run the test execute `cmake --build . --target test`.

### CODE REVIEW

**Comment by Sygmei** [comment]
@tim-gromeyer it appears that the test pipeline fails

**Comment by tim-gromeyer** [comment]
Setting the env variable `CTEST_OUTPUT_ON_FAILURE=1` and then `cmake --build . --target test` will solve the issue (I think).

**Comment by tim-gromeyer** [comment]
See

**Comment by Sygmei** [comment]
Awesome, build pipeline is fixed :)

Thanks a lot for your contribution !

**Review by Sygmei — APPROVED** [review]

**Pull request merged**
