### PR TITLE
Add UnitTests

### LINKED ISSUE #9: can't unzip zip files containing binary files
# description
zipfile only containing text files and folder structures work fine but if it also contains a binary file minizip-ng fails with error -109

# reproduction steps
1. download this file: 
   [patch.zip](https://github.com/Sygmei/11Zip/files/7758796/patch.zip)
2. try unziping it with this library.

library crashes while unzipping `Einkaufsliste.exe`

## expected behaviour
it should unzip the zip file without issues.

### PR DESCRIPTION
**Pull request by Assertores**
also fixes #9 

and also adds a `.clang-format` file

### CODE REVIEW

**Comment by Sygmei** [comment]
Hey @Assertores ! Thanks a lot for this PR.
I don't see what exactly fixed your issue, was it the unnecessary defines [here](https://github.com/Sygmei/11Zip/pull/10/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL12) ?
Also I don't think that embedding a zip containing an executable directly in the repository is a good idea, maybe that test CMake could build a dummy executable and zip it ? If you don't want to do it, I can handle this part.
Also the CI doesn't seem to run the tests, only build them ?

**Comment by Assertores** [comment]
yes removing the unnecessary `set()` solves the issue. the reason i added them in the first place was because ninja has issues building it without the `set()` but msvc and gcc (on linux) seam to work. therefore i removed them again.

i'll remove the zip and create it on the fly as you sayed.

**Comment by Assertores** [comment]
hi,
i added a `.clang-format` file and reformatted your code as well. i tried to stay as close to your original format as possible. would you mind checking if the code style is ok for you?

**Comment by Sygmei** [comment]
Looks really good to me, thanks a lot for this high-quality PR :)

**Pull request merged**
